# Generated by Django 5.0.8 on 2024-09-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='EDAD',
            field=models.IntegerField(max_length=10),
        ),
    ]
